/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
        
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'


export default function Jeep(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('./jeep.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group scale={0.1} >
        <mesh geometry={nodes.Cylinder018_Cylinder007.geometry} material={materials.Car} />
        <mesh geometry={nodes.Cylinder018_Cylinder007_1.geometry} material={materials.Windshield} />
      </group>
    </group>
  )
}

useGLTF.preload('./jeep.gltf');
