/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { forwardRef, useRef } from "react";
import { useGLTF } from "@react-three/drei";

const MustangWheel = (props, ref) => {
  const { nodes, materials } = useGLTF("/mustang-wheel.glb");
  return (
    <group {...props} ref={ref} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WheelsF_1.geometry}
        material={materials.Tire}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WheelsF_2.geometry}
        material={materials.Rim}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WheelsF_3.geometry}
        material={materials.RimUnder}
      />
    </group>
  );
}

useGLTF.preload("/mustang-wheel.glb");

export default forwardRef(MustangWheel);
