/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

function MustangFrame(props) {
  const { nodes, materials } = useGLTF("/mustang-frame.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Frame_1.geometry}
        material={materials.Paint}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Frame_2.geometry}
        material={materials.Windows}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Frame_3.geometry}
        material={materials.HeadLightEmission}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Frame_4.geometry}
        material={materials.AirIntake}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Frame_5.geometry}
        material={materials.FloorRail}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BackRail.geometry}
        material={materials.BorderWindow}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BackShield.geometry}
        material={materials.BorderWindow}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Handle.geometry}
        material={materials.BorderWindow}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.HoodRail.geometry}
        material={materials.BorderWindow}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SideWindow.geometry}
        material={materials.BorderWindow}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WindShield.geometry}
        material={materials.BorderWindow}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.TailLights_1.geometry}
        material={materials.TailLight}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.TailLights_2.geometry}
        material={materials.TailEmission}
      />
    </group>
  );
}

useGLTF.preload("/mustang-frame.glb");

export default MustangFrame;