/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Mustang(props) {
  const { nodes, materials } = useGLTF("/mustang.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle.geometry}
        material={materials.Paint}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle_1.geometry}
        material={materials.Windows}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle_2.geometry}
        material={materials.HeadLightEmission}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle_3.geometry}
        material={materials.AirIntake}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle_4.geometry}
        material={materials.FloorRail}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BackRail.geometry}
        material={materials.BorderWindow}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BackShield.geometry}
        material={materials.BorderWindow}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Handle.geometry}
        material={materials.BorderWindow}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.HoodRail.geometry}
        material={materials.BorderWindow}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SideWindow.geometry}
        material={materials.BorderWindow}
      />
      <group position={[0.57765466, 0.24000061, -0.96824157]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle001.geometry}
          material={materials.Tire}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle001_1.geometry}
          material={materials.Rim}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle001_2.geometry}
          material={materials.RimUnder}
        />
      </group>
      <group position={[0.57765466, 0.24000061, 1.06813729]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle001_3.geometry}
          material={materials.Tire}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle001_4.geometry}
          material={materials.Rim}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle001_5.geometry}
          material={materials.RimUnder}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WindShield.geometry}
        material={materials.BorderWindow}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle002.geometry}
        material={materials.TailLight}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle002_1.geometry}
        material={materials.TailEmission}
      />
    </group>
  );
}

export default Mustang;

useGLTF.preload("/mustang.glb");
